### PR TITLE
not clearing the add table causes inconsistencies during stochastic s…

### PR DESCRIPTION
**Pull request by 33Gjl1Xe**
…imulation

### CODE REVIEW

**Review by burgholzer — APPROVED** [review]
LGTM. The performance warning can safely be ignored.

**Review by hillmich — APPROVED** [review]
LGTM

**Review by burgholzer — COMMENTED** [review]
Did you test the proposed changes with the unit tests in the QFR?
If yes, is performance of Grover simulation and QFT functionality affected?
At the moment the garbage collection limit is automatically reduced whenever a collection took place and the remaining nodes are far less than the threshold.
If unique tables and the complex table have to be collected together this could lead to a large number of subsequent garbage collects.
We might want to turn the garbage collection limit reduction off for now.

**Comment by 33Gjl1Xe** [comment]
> 
> 
> Did you test the proposed changes with the unit tests in the QFR?
> If yes, is performance of Grover simulation and QFT functionality affected?
> At the moment the garbage collection limit is automatically reduced whenever a collection took place and the remaining nodes are far less than the threshold.
> If unique tables and the complex table have to be collected together this could lead to a large number of subsequent garbage collects.
> We might want to turn the garbage collection limit reduction off for now.

I did some tests and disabling the dynamic garbage collection limit seems like a good idea. I did some rudimentary tests on my virtual machine and disabling the dynamic garbage collection limit actually decreased the runtime of the QFT  (48s -> 42s) and Grover (28s->24s) unit tests of the new version with the bugfix, compared to the old version without the bugfix.

**Review by hillmich — APPROVED** [review]

**Review by burgholzer — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
